---
title: "Sistem Informasi Manajemen"
description: |
  Kode Mata Kuliah/SKS: EKMA4434/3 SKS
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
Tutor: [Tedy Herlambang](https://bangtedy.github.io)

### Sekilas SIM

Sistem informasi manajemen (SIM) merupakan sistem informasi yang menghasilkan keluaran (*output*) dengan menggunakan masukan (*input*) dan berbagai proses yang diperlukan untuk memenuhi tujuan tertentu dalam suatu kegiatan manajemen.

Mata kuliah SIM ini mencakup pembahasan mengenai konsep-konsep dasar informasi, basis data, aplikasi dalam pengambilan keputusan dan perkembangan sistem teknologi informasi, serta internet sebagai sarana penunjang kegiatan bisnis. Mahasiswa diharapkan mampu menjelaskan dan mengaplikasikan konsep dan teori buku materi pokok. 


### Sekilas Materi Tutorial

Tutorial dilakukan sebanyak 8 kali mencakup 9 modul. Topik-topik yang akan dibahas sebagai berikut:

:::obj

* Minggu 1. Konsep dasar sistem informasi
* Minggu 2. Konsep sistem informasi
* Minggu 3. Pengambilan keputusan manajemen dan informasi yang dibutuhkan
* Minggu 4. Aplikasi sistem informasi
* Minggu 5. Pengembangan sistem informasi
* Minggu 6. Teknologi sistem informasi
* Minggu 7. Basis data
* Minggu 8. Pengendalian sistem informasi; internet dan e-business

:::

### Rujukan utama:

- Jogiyanto (2018). Sistem Informasi Manajemen (BMP)/EKMA4434. Tangerang Selatan, Universitas Terbuka.

### Rujukan tambahan:

- Laudon, Kenneth C., and Jane P. Laudon (2017). Essentials of management information systems, Twelveth edition. Pearson.

- Sousa, Kenneth J. and Effy Oz (2015) Management Information Systems, Seventh Edition. Cengage Learning.


